This fixes a build error with any program using libsoundio-d and built using dub --combined and LDC
The error is the following:

    C:\Users\guill\Desktop\libsoundio-d>dub run --combined libsoundio-d:sine
    Building package libsoundio-d:sine in C:\Users\guill\Desktop\libsoundio-d\
    Performing "debug" build using C:\d\ldc2-1.27.0-beta3-windows-multilib\bin\ldc2.exe for x86_64.
    libsoundio-d:sine 1.0.0+commit.7.g67d2c03: building configuration "application"...
    source\soundio\api.d(1195,20): Error: Function type does not match previously declared function with the same mangled name: `soundio_ring_buffer_create`
    source\soundio\api.d(1195,20):        Previous IR type: %soundio.ring_buffer.SoundIoRingBuffer* (%soundio.api.SoundIo*, i32)
    source\soundio\api.d(1195,20):        New IR type:      %soundio.api.SoundIoRingBuffer* (%soundio.api.SoundIo*, i32)
    C:\d\ldc2-1.27.0-beta3-windows-multilib\bin\ldc2.exe failed with exit code 1.

This removes the forward declaration for ring-buffer, when built with LDC.
I'm not sure if this is an old LDC regression/bug, or legitimate error.